# Generated by Django 4.1.3 on 2022-11-11 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_manga_year_alter_translator_language_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manga',
            name='translator',
        ),
    ]
