# Generated by Django 4.1.3 on 2022-11-11 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_remove_manga_translator"),
    ]

    operations = [
        migrations.AlterField(
            model_name="translator",
            name="language",
            field=models.CharField(
                choices=[("EN", "England"), ("FR", "France"), ("GE", "Germany")],
                max_length=255,
            ),
        ),
    ]
